branches:
  except:
    - /^v[0-9]/
    - gh-pages

language: ruby

rvm:
  - 2.2.4

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

install:
  - gem install jekyll bundle
  - bundle install

script:
  - jekyll b

after_success:
  - cd _site
  - git init
  - git config user.name "Travis CI"
  - git config user.email "jarvis@resourceful-humans.com"
  - git add .
  - git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/ResourcefulHumans/hr2rh.com.git" master:gh-pages > /dev/null 2>&1
